# Generated by Django 3.2 on 2022-03-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('sauth', '0002_alter_shopuser_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
