# Generated by Django 3.2 on 2022-03-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sauth', '0003_alter_shopuser_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='name',
        ),
    ]
