# Generated by Django 3.2 on 2022-02-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureDetail',
            fields=[
                ('furniture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='furniture.furniture')),
                ('discription', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='furniture',
            options={'ordering': ['updated_at']},
        ),
    ]
